### tf.data.dataset 包含一系列数据

包含许多元素
创建方式：  
1、直接从tensorflow中创建 Dataset.from _tensor_slices()，numpy  
2、对多个dataset进行处理得到新的  
一个dataset对象包含多个元素，每个元素的结构都相同。每个元素包含一个或多个tf.tensor
对象，这些对象被成为组件。

对于这些可以直接迭代

In [1]:
import tensorflow as tf

In [3]:
data = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])#参数为列表或array

In [4]:
data

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
for ele in data:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [6]:
for ele in data:
    print(ele.numpy())

1
2
3
4
5
6


In [9]:
data2 = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])#参数为列表或array

In [14]:
data2

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [10]:
for ele in data2:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


In [13]:
for ele in data2:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [21]:
data3 = tf.data.Dataset.from_tensor_slices({'a':[1,2,3],
                                            'b':[4,5,6],
                                            'c':[12,13,14]})#参数为列表或array

In [22]:
data3

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [23]:
for ele in data3:
    print(ele)

{'a': <tf.Tensor: id=106, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=107, shape=(), dtype=int32, numpy=4>, 'c': <tf.Tensor: id=108, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=109, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=110, shape=(), dtype=int32, numpy=5>, 'c': <tf.Tensor: id=111, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=112, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=113, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=114, shape=(), dtype=int32, numpy=14>}


In [24]:
import numpy as np

In [26]:
data_arr = tf.data.Dataset.from_tensor_slices(np.array([[1,2],[3,4],[5,6]]))#参数为列表或array

In [27]:
for ele in data_arr:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)


In [29]:
for ele in data_arr.take(2):
    print(ele.numpy())

[1 2]
[3 4]


## dataset 的应用
1、shuffle

In [54]:
dataset = data_arr.shuffle(3)#选取多大数据量

In [55]:
for ele in dataset:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)


In [56]:
dataset = dataset.repeat(count=4)#重复三次shuffle

In [57]:
for ele in dataset:
    print(ele)

tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [58]:
dataset = dataset.batch(5)#切分成batch

In [59]:
for ele in dataset:
    print(ele)

tf.Tensor(
[[3 4]
 [1 2]
 [5 6]
 [5 6]
 [1 2]], shape=(5, 2), dtype=int64)
tf.Tensor(
[[3 4]
 [3 4]
 [5 6]
 [1 2]
 [5 6]], shape=(5, 2), dtype=int64)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [52]:
dataset = dataset.map(tf.square)

In [53]:
for ele in dataset:
    print(ele)

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
