### tf.data.dataset 包含一系列数据

包含许多元素
创建方式：  
1、直接从tensorflow中创建 Dataset.from _tensor_slices()，numpy  
2、对多个dataset进行处理得到新的  
一个dataset对象包含多个元素，每个元素的结构都相同。每个元素包含一个或多个tf.tensor
对象，这些对象被成为组件。

对于这些可以直接迭代

In [1]:
import tensorflow as tf

In [3]:
data = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])#参数为列表或array

In [4]:
data

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
for ele in data:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [6]:
for ele in data:
    print(ele.numpy())

1
2
3
4
5
6


In [9]:
data2 = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])#参数为列表或array

In [14]:
data2

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [10]:
for ele in data2:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


In [13]:
for ele in data2:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [21]:
data3 = tf.data.Dataset.from_tensor_slices({'a':[1,2,3],
                                            'b':[4,5,6],
                                            'c':[12,13,14]})#参数为列表或array

In [22]:
data3

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [23]:
for ele in data3:
    print(ele)

{'a': <tf.Tensor: id=106, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=107, shape=(), dtype=int32, numpy=4>, 'c': <tf.Tensor: id=108, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=109, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=110, shape=(), dtype=int32, numpy=5>, 'c': <tf.Tensor: id=111, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=112, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=113, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=114, shape=(), dtype=int32, numpy=14>}


In [24]:
import numpy as np

In [26]:
data_arr = tf.data.Dataset.from_tensor_slices(np.array([[1,2],[3,4],[5,6]]))#参数为列表或array

In [27]:
for ele in data_arr:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)


In [29]:
for ele in data_arr.take(2):
    print(ele.numpy())

[1 2]
[3 4]


## dataset 的应用
1、shuffle

In [54]:
dataset = data_arr.shuffle(3)#选取多大数据量

In [55]:
for ele in dataset:
    print(ele)

tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)


In [56]:
dataset = dataset.repeat(count=4)#重复三次shuffle

In [57]:
for ele in dataset:
    print(ele)

tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([3 4], shape=(2,), dtype=int64)
tf.Tensor([5 6], shape=(2,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [58]:
dataset = dataset.batch(5)#切分成batch

In [59]:
for ele in dataset:
    print(ele)

tf.Tensor(
[[3 4]
 [1 2]
 [5 6]
 [5 6]
 [1 2]], shape=(5, 2), dtype=int64)
tf.Tensor(
[[3 4]
 [3 4]
 [5 6]
 [1 2]
 [5 6]], shape=(5, 2), dtype=int64)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [52]:
dataset = dataset.map(tf.square)

In [53]:
for ele in dataset:
    print(ele)

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


## tf.dataset  的应用

In [28]:
(train_img,train_lab),(test_img,test_lab) = tf.keras.datasets.mnist.load_data()

In [29]:
train_img = train_img/255
test_img = test_img/255

In [4]:
ds_train_img = tf.data.Dataset.from_tensor_slices(train_img)

In [5]:
ds_test_img = tf.data.Dataset.from_tensor_slices(test_img)

In [6]:
ds_train_img

<TensorSliceDataset shapes: (28, 28), types: tf.float64>

In [7]:
ds_train_lab = tf.data.Dataset.from_tensor_slices(train_lab)
ds_test_lab = tf.data.Dataset.from_tensor_slices(test_lab)

In [8]:
ds_train_lab

<TensorSliceDataset shapes: (), types: tf.uint8>

可以直接放入,不需要每个都作dataset，也就是说可以直接跳过上几个步骤，直接这一步

In [30]:
ds_train = tf.data.Dataset.zip((ds_train_img,ds_train_lab))
ds_test = tf.data.Dataset.zip((ds_test_img,ds_test_lab))

注意训练集和测试集的区别

In [31]:
ds_train = ds_train.shuffle(10000).repeat().batch(64)
ds_test = ds_test.batch(64)

In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax')
])

In [14]:
model.compile(optimizer='adam',
             loss=tf.keras.losses.sparse_categorical_crossentropy,
             metrics=['accuracy'])

In [32]:
batch_size=64
steps_per_epoch = train_img.shape[0]/batch_size

In [33]:
steps_per_epoch

937.5

In [34]:
history = model.fit(ds_train,epochs=5,steps_per_epoch=steps_per_epoch,
                   validation_data=ds_test,
                   validation_steps=test_img.shape[0]/batch_size)

Train for 937.5 steps, validate for 156.25 steps
Epoch 1/5
938/937 [==============================] - 2s 2ms/step - loss: 0.0462 - accuracy: 0.9863 - val_loss: 0.0829 - val_accuracy: 0.9756
Epoch 2/5
938/937 [==============================] - 2s 2ms/step - loss: 0.0377 - accuracy: 0.9888 - val_loss: 0.0711 - val_accuracy: 0.9778
Epoch 3/5
938/937 [==============================] - 2s 2ms/step - loss: 0.0305 - accuracy: 0.9911 - val_loss: 0.0784 - val_accuracy: 0.9763
Epoch 4/5
938/937 [==============================] - 2s 2ms/step - loss: 0.0250 - accuracy: 0.9931 - val_loss: 0.0770 - val_accuracy: 0.9777
Epoch 5/5
938/937 [==============================] - 2s 2ms/step - loss: 0.0207 - accuracy: 0.9942 - val_loss: 0.0744 - val_accuracy: 0.9790


In [21]:
history.history['accuracy']

[0.91806036, 0.9611207, 0.97254795, 0.9788946, 0.9829424]